# YAML template for ibm-ban-secret secret
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: ibm-ban-secret
  # DO NOT change the content of metadata.labels
  labels:
    db-server: dbserver1
    db-name: icndb
stringData:
  appLoginUsername: "CEAdmin"
  appLoginPassword: "Genius1"
  navigatorDBUsername: db2inst1
  navigatorDBPassword: Psiadmin1
  jMailUsername: "<JMAIL_ADMIN>"
  jMailPassword: "<JMAIL_PASSWORD>"
  ltpaPassword: "Genius1"
  keystorePassword: "Genius1"
