################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-baw-operator
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/cp4a/ibm-cs-bawautomation-catalog:2302-latest
  updateStrategy:
    registryPoll:
      interval: 45m

