echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ae/ibm-playback-server-admin-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ae/ibm-playback-server-admin-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ae/ibm-aae-app-engine-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ae/ibm-aae-app-engine-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/adp/ibm-adp-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/adp/ibm-adp-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/bas/ibm-bas-admin-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/bas/ibm-bas-admin-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ldap-bind-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ldap-bind-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ban/ibm-ban-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/ban/ibm-ban-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/fncm/ibm-fncm-icc-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/fncm/ibm-fncm-icc-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Applying YAML template file:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/fncm/ibm-fncm-secret.yaml"
kubectl apply -f "/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/fncm/ibm-fncm-secret.yaml"
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

echo "****************************************************************************"
echo "******************************* START **************************************"
echo "[INFO] Executing shell script:/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/adp/ibm-aca-db-secret.sh"
/Users/snguyen/Documents/cert-kube/cert-kube-2302/cert-kubernetes/scripts/cp4ba-prerequisites/secret_template/adp/ibm-aca-db-secret.sh
echo "******************************** END ***************************************"
echo "****************************************************************************"
printf "\n"

