# YAML template for ibm-fncm-secret secret
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: ibm-fncm-secret
  # DO NOT change the content of metadata.labels
  labels:
    gcd-db-server: dbserver1
    db-name: ibm-fncm-secret
stringData:
  appLoginUsername: "CEAdmin"
  appLoginPassword: "Genius1"
  gcdDBUsername: db2inst1
  gcdDBPassword: Psiadmin1
  devos1DBUsername: db2inst1
  devos1DBPassword: Psiadmin1
  aeosDBUsername: db2inst1
  aeosDBPassword: Psiadmin1
  os1DBUsername: db2inst1
  os1DBPassword: Psiadmin1
  ltpaPassword: "Genius1"
  keystorePassword: "Genius1"
