###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2022. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-content-operator
  labels:
    app.kubernetes.io/instance: ibm-dba-content
    app.kubernetes.io/managed-by: ibm-dba-content
    app.kubernetes.io/name: ibm-dba-content
    release: 23.0.2
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - restricted
  resources:
  - securitycontextconstraints
  verbs:
  - use
  - list
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  - ingresses
  verbs:
  - get
  - list
  - update
  - create
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - persistentvolumes
  verbs:
  - get
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - operator.ibm.com
  resources:
  - operandrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - operandrequests/status
  verbs:
  - get
- apiGroups:
  - operator.ibm.com
  resources:
  - commonservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - get
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db2u.databases.ibm.com
  resources:
  - db2uclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db2u.databases.ibm.com/v1
  resources:
  - db2uclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db2u.databases.ibm.com
  resources:
  - db2uclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db2u.databases.ibm.com/v1.Db2uCluster
  resources:
  - db2uclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - businessteamsservices
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - apiextensions.k8s.io
  verbs:
  - get
  - list
  resources:
  - customresourcedefinitions
- apiGroups:
  - oidc.security.ibm.com
  resources:
  - clients
  verbs:
  - delete
  - list
  - get
  - create
